import { SourceCommitNode, Branch } from "./grid";

export const SIMPLE_BRANCHES: Array<Branch> = [
    {
        id: "main",
        name: "Main",
        baseBranchId: null,
        createdBy: "user1",
        lastCommit: "C",
        createdAt: "Sat Jan 01 2000 00:00:00 GMT-0800",
    },
    {
        id: "feature",
        name: "Feature",
        baseBranchId: "main",
        createdBy: "user1",
        lastCommit: "E",
        createdAt: "Sat Jan 01 2000 00:00:00 GMT-0800",
    },
    {
        id: "feature-x",
        name: "Feature X",
        baseBranchId: "feature",
        createdBy: "user1",
        lastCommit: "Y",
        createdAt: "Sat Jan 01 2000 00:00:00 GMT-0800",
    },
    {
        id: "side-feature",
        name: "Side Feature",
        baseBranchId: "main",
        createdBy: "user1",
        lastCommit: "G",
        createdAt: "Sat Jan 01 2000 00:00:00 GMT-0800",
    },
    {
        id: "side-feature-2",
        name: "Side Feature 2",
        baseBranchId: "main",
        createdBy: "user1",
        lastCommit: "H",
        createdAt: "Sat Jan 01 2000 00:00:00 GMT-0800",
    },
    {
        id: "main-disjoint",
        name: "Main Disjoint",
        baseBranchId: null,
        createdBy: "user1",
        lastCommit: "M0",
        createdAt: "Sat Jan 01 2000 00:00:00 GMT-0800",
    },
    {
        id: "feature-disjoint",
        name: "Feature Disjoint",
        baseBranchId: "main-disjoin",
        createdBy: "user1",
        lastCommit: "DD0",
        createdAt: "Sat Jan 01 2000 00:00:00 GMT-0800",
    },
]

export const SIMPLE_MAIN_HISTORY: Array<SourceCommitNode> = [
  {
    sha: "A",
    timestamp: "Sat Jan 01 2000 00:00:00 GMT-0800",
    message: "test",
    userId: "user1",
    authorUserId: "user1",
    parent: null,
    mergeBase: null,
    historicalParent: null,
    idx: 0,
    branchIds: [
      "main",
      "feature",
      "feature-x",
      "side-feature",
      "side-feature-2",
    ],
    children: [
      {
        sha: "B",
        timestamp: "Sat Jan 01 2000 00:00:02 GMT-0800",
        message: "test",
        userId: "user1",
        authorUserId: "user1",
        parent: "A",
        mergeBase: null,
        historicalParent: "A",
        idx: 1,
        branchIds: ["main", "feature", "feature-x"],
        children: [
          {
            sha: "C",
            timestamp: "Sat Jan 01 2000 00:00:03 GMT-0800",
            message: "test",
            userId: "user1",
            authorUserId: "user1",
            parent: "B",
            mergeBase: null,
            historicalParent: "B",
            idx: 2,
            branchIds: ["main"],
          },
          {
            sha: "D",
            timestamp: "Sat Jan 01 2000 00:00:02 GMT-0800",
            message: "test",
            userId: "user1",
            authorUserId: "user1",
            parent: "B",
            mergeBase: null,
            historicalParent: "B",
            idx: 2,
            branchIds: ["feature", "feature-x"],
            children: [
              {
                sha: "E",
                timestamp: "Sat Jan 01 2000 00:00:02 GMT-0800",
                message: "test",
                userId: "user1",
                authorUserId: "user1",
                parent: "D",
                mergeBase: null,
                historicalParent: "D",
                idx: 3,
                branchIds: ["feature", "feature-x"],
                children: [
                  {
                    sha: "X",
                    timestamp: "Sat Jan 01 2000 00:00:02 GMT-0800",
                    message: "test",
                    userId: "user1",
                    authorUserId: "user1",
                    parent: "E",
                    mergeBase: null,
                    historicalParent: "E",
                    idx: 4,
                    branchIds: ["feature-x"],
                    children: [
                      {
                        sha: "Y",
                        timestamp: "Sat Jan 01 2000 00:00:02 GMT-0800",
                        message: "test",
                        userId: "user1",
                        authorUserId: "user1",
                        parent: "X",
                        mergeBase: null,
                        historicalParent: "X",
                        idx: 5,
                        branchIds: ["feature-x"],
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        sha: "F",
        timestamp: "Sat Jan 01 2000 00:00:02 GMT-0800",
        message: "test",
        userId: "user1",
        authorUserId: "user1",
        parent: "A",
        mergeBase: null,
        historicalParent: "A",
        idx: 1,
        branchIds: ["side-feature", "side-feature-2"],
        children: [
          {
            sha: "G",
            timestamp: "Sat Jan 01 2000 00:00:02 GMT-0800",
            message: "test",
            userId: "user1",
            authorUserId: "user1",
            parent: "F",
            mergeBase: null,
            historicalParent: "F",
            idx: 2,
            branchIds: ["side-feature", "side-feature-2"],
            children: [
              {
                sha: "H",
                timestamp: "Sat Jan 01 2000 00:00:02 GMT-0800",
                message: "test",
                userId: "user1",
                authorUserId: "user1",
                parent: "G",
                mergeBase: null,
                historicalParent: "G",
                idx: 3,
                branchIds: ["side-feature-2"],
              },
            ],
          },
        ],
      },
      {
        sha: "R",
        timestamp: "Sat Jan 01 2000 00:00:03 GMT-0800",
        message: "test",
        userId: "user1",
        authorUserId: "user1",
        parent: "A",
        mergeBase: null,
        historicalParent: "A",
        idx: 2,
        branchIds: [],
      },
    ],
  },
  {
    sha: "A0",
    timestamp: "Sat Jan 01 2000 00:00:00 GMT-0800",
    message: "test",
    userId: "user1",
    authorUserId: "user1",
    parent: null,
    mergeBase: null,
    historicalParent: null,
    idx: 0,
    branchIds: ["main-disjoint", "feature-disjoint"],
    children: [
      {
        sha: "B0",
        timestamp: "Sat Jan 01 2000 00:00:02 GMT-0800",
        message: "test",
        userId: "user1",
        authorUserId: "user1",
        parent: "A0",
        mergeBase: null,
        historicalParent: "A0",
        idx: 1,
        branchIds: ["main-disjoint", "feature-disjoint"],
        children: [
          {
            sha: "M0",
            timestamp: "Sat Jan 01 2000 00:00:02 GMT-0800",
            message: "test",
            userId: "user1",
            authorUserId: "user1",
            parent: "B0",
            mergeBase: null,
            historicalParent: "B0",
            idx: 2,
            branchIds: ["main-disjoint"],
          },
          {
            sha: "X0",
            timestamp: "Sat Jan 01 2000 00:00:02 GMT-0800",
            message: "test",
            userId: "user1",
            authorUserId: "user1",
            parent: "B0",
            mergeBase: null,
            historicalParent: "B0",
            idx: 2,
            branchIds: [],
            children: [
              {
                sha: "Y0",
                timestamp: "Sat Jan 01 2000 00:00:02 GMT-0800",
                message: "test",
                userId: "user1",
                authorUserId: "user1",
                parent: "X0",
                mergeBase: null,
                historicalParent: "X0",
                idx: 3,
                branchIds: [],
                children: [
                  {
                    sha: "Z0",
                    timestamp: "Sat Jan 01 2000 00:00:02 GMT-0800",
                    message: "test",
                    userId: "user1",
                    authorUserId: "user1",
                    parent: "Y0",
                    mergeBase: null,
                    historicalParent: "Y0",
                    idx: 4,
                    branchIds: [],
                  },
                ],
              },
            ],
          },
          {
            sha: "X1",
            timestamp: "Sat Jan 01 2000 00:00:02 GMT-0800",
            message: "test",
            userId: "user1",
            authorUserId: "user1",
            parent: "B0",
            mergeBase: null,
            historicalParent: "B0",
            idx: 2,
            branchIds: [],
            children: [
              {
                sha: "Y1",
                timestamp: "Sat Jan 01 2000 00:00:02 GMT-0800",
                message: "test",
                userId: "user1",
                authorUserId: "user1",
                parent: "X1",
                mergeBase: null,
                historicalParent: "X1",
                idx: 3,
                branchIds: [],
                children: [
                  {
                    sha: "Z1",
                    timestamp: "Sat Jan 01 2000 00:00:02 GMT-0800",
                    message: "test",
                    userId: "user1",
                    authorUserId: "user1",
                    parent: "Y1",
                    mergeBase: null,
                    historicalParent: "Y1",
                    idx: 4,
                    branchIds: [],
                  },
                ],
              },
            ],
          },
          {
            sha: "CD0",
            timestamp: "Sat Jan 01 2000 00:00:02 GMT-0800",
            message: "test",
            userId: "user1",
            authorUserId: "user1",
            parent: "B0",
            mergeBase: null,
            historicalParent: "B0",
            idx: 2,
            branchIds: ["feature-disjoint"],
            children: [
              {
                sha: "DD0",
                timestamp: "Sat Jan 01 2000 00:00:02 GMT-0800",
                message: "test",
                userId: "user1",
                authorUserId: "user1",
                parent: "CD0",
                mergeBase: null,
                historicalParent: "CD0",
                idx: 3,
                branchIds: ["feature-disjoint"],
              },
            ],
          },
        ],
      },
    ],
  },
];
