name: Build & Test

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: postgres
          POSTGRES_DB: floro_test
          POSTGRES_HOST_AUTH_METHOD: trust

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    steps:
      # run steps required in the workflow
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16

      #- name: Add Floro CLI
      #  run: npm install -g floro

      #- name: Echo floro version
      #  run: echo "$(floro --version)"

      - name: Yarn install cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Install dependencies
        run: yarn

      #- name: Build Floro Assets
      #  working-directory: packages/common-generators
      #  run: floro module build
      #  env:
      #    ACTIONS_RUNNER_DEBUG: true
      #    FLORO_REMOTE_API_KEY: ${{ secrets.FLORO_REMOTE_API_KEY }}

      - name: Build Project
        run: yarn build:all

      - name: Run tests
        run: yarn test
        env:
          DBURL: postgres://postgres:postgres@localhost:5432/floro_test
          # The hostname used to communicate with the Redis service container
          REDIS_HOST: localhost
          # The default Redis port
          REDIS_PORT: 6379