name: Create Electron Release

on:
  release:
    types: [created]

defaults:
  run:
    shell: 'bash'

jobs:
  release_electron:
    name: 'Create Electron Release'

    permissions:
      contents: write

    strategy:
      fail-fast: true
      matrix:
        os: [ macos-12, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - name: Yarn install cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Install dependencies
        run: yarn

      - name: Build Graph QL
        run: yarn graphql-schemas:build
      - name: Install rpm
        if: runner.os == 'Linux'
        run: sudo apt-get install -y rpm
        shell: bash

      - name: Install Electron dependencies
        working-directory: packages/floro-desktop
        run: |
          yarn install
          yarn postinstall:manual
      - name: Install Electron dependencies
        working-directory: packages/floro-desktop
        run: yarn build
        env:
          BUILD_ENV: prod

      - name: Compile prod artifacts and upload them to github release
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 6
          retry_wait_seconds: 15
          retry_on: error
          shell: 'bash'
          command: |
            cd packages/floro-desktop
            npx --no-install electron-builder --config .electron-builder.config.js --publish 'always'
        env:
          BUILD_ENV: prod
          TEAM_ID: ${{secrets.TEAM_ID}}
          APPLE_ID: ${{secrets.APPLE_ID}}
          APPLE_APP_SPECIFIC_PASSWORD: ${{secrets.APPLE_APP_SPECIFIC_PASSWORD}}
          APPLE_ID_PASS: ${{secrets.APPLE_ID_PASS}}
          CSC_LINK: ${{secrets.CSC_LINK}}
          CSC_KEY_PASSWORD: ${{secrets.CSC_KEY_PASSWORD}}
          GH_TOKEN: ${{ secrets.github_token }}

      - uses: actions/upload-artifact@v3
        with:
          name: Mac Artifact
          path: packages/floro-desktop/dist/*.dmg
        env:
          GH_TOKEN: ${{ secrets.github_token }}

      - uses: actions/upload-artifact@v3
        with:
          name: Windows Artifact
          path: packages/floro-desktop/dist/*.exe
        env:
          GH_TOKEN: ${{ secrets.github_token }}

      - uses: actions/upload-artifact@v3
        with:
          name: Debian Artifact
          path: packages/floro-desktop/dist/*.deb
        env:
          GH_TOKEN: ${{ secrets.github_token }}

      - uses: actions/upload-artifact@v3
        with:
          name: RPM Artifact
          path: packages/floro-desktop/dist/*.rpm
        env:
          GH_TOKEN: ${{ secrets.github_token }}