name: Create Build

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Build Environment'
        required: true
        default: staging
        type: choice
        options:
          - staging
          - prod
jobs:
  sync-artifacts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: haya14busa/action-cond@v1
        id: bucketName
        with:
          cond: ${{ github.event.inputs.buildType == 'prod' }}
          if_true: 'floro-static-assets-prod'
          if_false: 'floro-static-assets-staging'
      - uses: haya14busa/action-cond@v1
        id: cdnHost
        with:
          cond: ${{ github.event.inputs.buildType == 'prod' }}
          if_true: 'https://static-cdn.floro.com'
          if_false: 'https://static-cdn.floro-staging.com'
      - run: echo "CDN_HOST ${{ steps.cdnHost.outputs.value }}"
      - name: Yarn install cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Install dependencies
        run: yarn

      - name: Build Main
        run: CDN_HOST=${{ steps.cdnHost.outputs.value }} yarn build:main

      - name: Push build to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ steps.bucketName.outputs.value }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'packages/main/dist/client'