name: Create build

on:
  workflow_dispatch:
    inputs:
      buildEnv:
        description: "Build Environment"
        type: choice
        default: "staging"
          options:
            - "staging"
            - "prod"
jobs:
  sync-artifacts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: haya14busa/action-cond@v1
        id: bucketName
        with:
          cond: ${{ github.event.inputs.buildEnv == 'prod' }}
          if_true: "floro-static-assets-prod"
          if_false: "floro-static-assets-staging"
      - run: echo "Syncing to bucket ${{ steps.bucketName.outputs.value }}"